### ISSUE TITLE
Crashing in singleplayer 1.17.1

### ISSUE THREAD

**Issue by white-devil42** [jensvh/litematica-printer#10]
when i try to place a block with easy place turned on it just crashes 
edit:
crash report
---- Minecraft Crash Report ----
// There are four lights!

Time: 23/11/21, 3:33 pm
Description: Unexpected error

java.lang.NoSuchMethodError: 'fi.dy.masa.litematica.util.RayTraceUtils$RayTraceWrapper fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(net.minecraft.class_1937, net.minecraft.class_1297, double, boolean)'
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:204)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java:1080)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:395)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:267)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$zdi000$hookOnMouseClick(class_312.java:556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:204)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java:1080)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:395)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:267)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$zdi000$hookOnMouseClick(class_312.java:556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)

-- Affected level --
Details:
	All players: 1 total; [class_746['RamugtGT'/71, l='ClientLevel', x=135.02, y=61.73, z=11.26]]
	Chunk stats: 841, 550
	Level dimension: minecraft:overworld
	Level spawn location: World: (168,-1,8), Section: (at 8,15,8 in 10,-1,0; chunk contains blocks 160,0,0 to 175,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1167068 game time, 3000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1729704648 bytes (1649 MiB) / 2550136832 bytes (2432 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14057.16
	Virtual memory used (MB): 9915.00
	Swap memory total (MB): 6000.00
	Swap memory used (MB): 499.45
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		atomic: Atomic client 1.0.0
		baritone: Baritone 1.7.0
		bedrockminer: Bedrock Miner 1.0.0
		blue_endless_jankson: jankson 1.2.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		club_minnced_java-discord-rpc: java-discord-rpc 2.0.1
		cmdkeybind: Command Macros 1.5.2-1.17
		com_github_hube12_seed: SEED master-SNAPSHOT
		customskinloader: CustomSkinLoader 14.13-SNAPSHOT-282
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		litematica: Litematica 0.0.0-dev.20210906.183617
		litematica_printer: Litematica Printer 2.0.0
		malilib: MaLiLib 0.10.0-dev.24
		meteor-client: Meteor Client 0.4.5
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.5
		multiconnect: MultiConnect 1.4.15
		multiconnect-api: MultiConnect API 1.4.15
		seedcrackerx: Seed Cracker X 2.9.0
		seedcrackerx-api: SeedCrackerX API 2.10.1
		shulkerdupe: Shulker dupe mod 1.0.0
		worldedit: WorldEdit 7.2.6+4b2d1e7
	Launched Version: Fabric 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.8681, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 258
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Player Count: 1 / 8; [class_3222['RamugtGT'/71, l='ServerLevel[Rexx & T2 - n:m Item Shop]', x=135.02, y=61.73, z=11.26]]
	Data Packs: vanilla, file/bukkit (incompatible), Fabric Mods

-- Meteor Client --
Version: 0.4.5

[Render]:
Tracers (tracers)

**Comment by jensvh** [comment]
A few functions were changed in the new litematica version.
The latest release should now be compatible with the latest malilib & litematica versions.
